<a href="https://colab.research.google.com/github/tarsojabbes/data-visualization/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NumPy**

## **Arithmetic Functions**

In [2]:
import numpy as np

In [3]:
a = np.arange(10)

In [5]:
b = np.random.randint(0,10,(1,10)) # From 0 to 9 in the shape of 1 by 10

In [8]:
c = a[np.newaxis, :]
print(c.shape) # Now, C will be also 1 by 10, meanwhile a is (10,)

(1, 10)


In [11]:
d = b + c
print(d)

[[ 3 10  3 11 12  6 15  7  9 11]]


In [12]:
d = d.squeeze # it'll supress the newaxis created before

Add Function -> It'll add two array into one; it's the same as b + c, no differencec.

In [17]:
e = np.add(b, c)
print(e)

[[ 3 10  3 11 12  6 15  7  9 11]]


Sum Function -> It'll sum all the values of a given array.

In [19]:
f = np.sum(b)
print(f)

42


In [21]:
g = np.arange(100).reshape(2,2,5,5) # 4D array, axis will go from 0 to 3

In [22]:
h =  g.sum(axis=0) # We'll lose the first dimension, and this will return a 2 by 5 by 5 array

Subtract Function -> It'll subtract the values of two given arrays by they respective relative by the index.

In [25]:
i = np.random.rand(10)
j = np.random.rand(10)
k = np.subtract(i,j)
print(k)

[-0.564153   -0.86104192  0.16573159 -0.1406437  -0.1646671  -0.21734146
  0.08995004  0.44351403  0.39149186  0.15191282]


Multiply Function

In [26]:
l = np.multiply(i,j)
print(l)

[0.1442083  0.13659029 0.22339064 0.45634476 0.34291543 0.0610035
 0.00084339 0.37901794 0.01296415 0.00287046]


Power function

In [28]:
m = np.power(i,j)
print(m)

[0.28644605 0.13744346 0.79591886 0.68943842 0.6344975  0.50112664
 0.9803539  0.94439364 0.97387001 0.97022939]


## **Trigonometric Functions**

In [29]:
n = np.random.rand(5)

Sin Function

In [30]:
np.sin(n)

array([0.22150271, 0.49967373, 0.39333463, 0.55288005, 0.47365397])

Cos Function

In [31]:
np.cos(n)

array([0.97515976, 0.86621369, 0.91939538, 0.83326085, 0.88071103])

Arcsin Function

In [32]:
np.arcsin(n)

array([0.22525527, 0.55062749, 0.416165  , 0.62588735, 0.51603468])

## **Logical Operators**

Greater Function

In [36]:
o = np.random.rand(10)
p = np.random.rand(10)

q = np.greater(o,p)
print(q)

[ True  True False  True False  True False  True  True False]


Not Operator

In [44]:
r = ~q
r = np.logical_not(q)
print(r)

[False False  True False  True False  True False False  True]


## **Missing Values**

np.nan can be used to add NaN values to an array

In [45]:
s = np.random.rand(10)
s[3] = np.nan

In [46]:
s

array([0.86910584, 0.08972203, 0.31614856,        nan, 0.6778681 ,
       0.93741609, 0.29976402, 0.4014397 , 0.10804205, 0.88298934])

np.isnan() will return an array with True if a value is NaN or false if it's not

In [48]:
np.isnan(s)

array([False, False, False,  True, False, False, False, False, False,
       False])

Normally, sum all the values of an array when we have a NaN value will return "nan", but we can use the nansum to do so.

In [50]:
np.sum(s)

nan

In [51]:
np.nansum(s)

4.582495728911073

## **Rounding Floating point numbers**

np.floor() will round the values down

In [54]:
t = 10 * np.random.rand(100)
print(t)

[5.99877215 6.6935814  9.17262744 2.08335014 9.28774822 4.52298132
 9.03330805 3.21274312 7.87421898 4.43363321 4.1072582  7.54532379
 5.79702495 2.94164492 6.00158805 5.48263583 9.29950747 9.64919032
 2.75644417 5.56677289 8.82596885 1.48783208 1.28582115 0.12187295
 5.09012495 5.03337568 1.9550052  9.29754287 2.25551265 9.24054081
 5.514022   1.51736792 2.10658674 6.26732254 7.22556626 0.87757482
 4.37136472 5.26863999 2.38741567 8.42503212 3.94971725 6.04108655
 6.87681759 8.17692136 3.83481443 0.95634536 4.82899918 3.62877796
 8.32364972 1.62744185 9.2473153  0.60919951 9.38235342 0.19727958
 6.60905439 8.32376748 2.1092417  1.28232985 6.75909878 0.43133578
 6.39358432 5.73361506 5.61408756 4.00379483 8.20726613 8.40006985
 5.19001445 5.79633585 6.80644145 5.16754752 4.91208467 1.78207192
 7.03252034 1.22804441 4.14532305 3.54036316 4.58874516 6.35846132
 1.58095265 2.97603605 0.89036441 3.90166565 2.37303411 4.87977415
 5.30832362 2.1508477  1.75634664 8.50808852 7.51081625 1.4176

In [55]:
np.floor(t)

array([5., 6., 9., 2., 9., 4., 9., 3., 7., 4., 4., 7., 5., 2., 6., 5., 9.,
       9., 2., 5., 8., 1., 1., 0., 5., 5., 1., 9., 2., 9., 5., 1., 2., 6.,
       7., 0., 4., 5., 2., 8., 3., 6., 6., 8., 3., 0., 4., 3., 8., 1., 9.,
       0., 9., 0., 6., 8., 2., 1., 6., 0., 6., 5., 5., 4., 8., 8., 5., 5.,
       6., 5., 4., 1., 7., 1., 4., 3., 4., 6., 1., 2., 0., 3., 2., 4., 5.,
       2., 1., 8., 7., 1., 7., 3., 8., 0., 5., 6., 1., 0., 2., 0.])

Meanwhile, np.ceil() will round the values up

In [56]:
np.ceil(t)

array([ 6.,  7., 10.,  3., 10.,  5., 10.,  4.,  8.,  5.,  5.,  8.,  6.,
        3.,  7.,  6., 10., 10.,  3.,  6.,  9.,  2.,  2.,  1.,  6.,  6.,
        2., 10.,  3., 10.,  6.,  2.,  3.,  7.,  8.,  1.,  5.,  6.,  3.,
        9.,  4.,  7.,  7.,  9.,  4.,  1.,  5.,  4.,  9.,  2., 10.,  1.,
       10.,  1.,  7.,  9.,  3.,  2.,  7.,  1.,  7.,  6.,  6.,  5.,  9.,
        9.,  6.,  6.,  7.,  6.,  5.,  2.,  8.,  2.,  5.,  4.,  5.,  7.,
        2.,  3.,  1.,  4.,  3.,  5.,  6.,  3.,  2.,  9.,  8.,  2.,  8.,
        4.,  9.,  1.,  6.,  7.,  2.,  1.,  3.,  1.])